# Sample Grafana config
# Config assumes that prometheus server is reachable at that name. Change if needed

apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  url: http://prometheus:9090 
  isDefault: true
  access: proxy
  editable: true
