# Sample prometheus server config. Change as needed
# If you only need the exporter section remove global, alerting and the prometheus job

global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2

scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

  # Second sun exporter. Change port if needed
- job_name: 'pi-second-sun'
  scrape_interval: 15s
  static_configs:
  - targets: ['pi.casa:8000']
