{
 "title": "Second sun",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Final Brightness",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "second_sun_light_brightness", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hour-In-Day Factor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    { "expr": "second_sun_light_progress_day", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Day-in-Year factor",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "second_sun_absolute_light_year", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Is light on?",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 17, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "second_sun_light_is_on", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Service Running",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"pi-second-sun\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}